package poo.arcade.testproyecto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;
import poo.clases.proyecto.Arcade;

/**
 *
 * @author USUARIO
 */
public class GUIArcade extends javax.swing.JFrame {
    Arcade arcade;
    private double cobro;
    

    /**
     * Creates new form GUIArcade
     */
    public GUIArcade() {
        initComponents();
        btnGuardarCobro.setEnabled(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgNumJugadores = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmbArcade = new javax.swing.JComboBox<>();
        lblArcade = new javax.swing.JLabel();
        lblNumJugadores = new javax.swing.JLabel();
        rbt1 = new javax.swing.JRadioButton();
        rbt2 = new javax.swing.JRadioButton();
        btnCalcularpago = new javax.swing.JButton();
        btnGuardarCobro = new javax.swing.JButton();
        btnCancelarCobro = new javax.swing.JButton();
        lblHorasAlquiladas = new javax.swing.JLabel();
        txtHorasAlquiladas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Arcade");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Arcade"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbArcade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arcade deportivo", "Arcade carreras", "Arcade simulación", "Arcade acción", "Arcade clasico" }));
        cmbArcade.setSelectedIndex(-1);
        jPanel1.add(cmbArcade, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 155, -1));

        lblArcade.setForeground(new java.awt.Color(255, 255, 255));
        lblArcade.setText("Arcade:");
        jPanel1.add(lblArcade, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, 20));

        lblNumJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblNumJugadores.setText("Número de jugadores:");
        jPanel1.add(lblNumJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 20));

        rbt1.setBackground(new java.awt.Color(204, 204, 255));
        btgNumJugadores.add(rbt1);
        rbt1.setForeground(new java.awt.Color(255, 255, 255));
        rbt1.setText("1");
        rbt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(rbt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 40, 20));

        rbt2.setBackground(new java.awt.Color(204, 204, 255));
        btgNumJugadores.add(rbt2);
        rbt2.setForeground(new java.awt.Color(255, 255, 255));
        rbt2.setText("2");
        rbt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(rbt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 40, 20));

        btnCalcularpago.setText("Calcular Cobro");
        btnCalcularpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularpagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        btnGuardarCobro.setText("Guardar Cobro");
        btnGuardarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCobroActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        btnCancelarCobro.setText("Cancelar Cobro");
        btnCancelarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCobroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        lblHorasAlquiladas.setForeground(new java.awt.Color(255, 255, 255));
        lblHorasAlquiladas.setText("Horas alquiladas:");
        jPanel1.add(lblHorasAlquiladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 20));
        jPanel1.add(txtHorasAlquiladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 48, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/background/LogoAZMarco.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularpagoActionPerformed
        // TODO add your handling code here:
         try{
            if(llenos()){
                int horasAlquiladas=Integer.parseInt(txtHorasAlquiladas.getText());
                String tipoDeArcade= (String) cmbArcade.getSelectedItem();
                bloquearCampos();
                arcade=new Arcade();
                arcade.setTipoDeArcade(tipoDeArcade);
                arcade.setHorasDealquiler(horasAlquiladas);  
                if(rbt1.isSelected()){
                    arcade.setNumJugadores(1);
                }
                if(rbt2.isSelected()){
                    arcade.setNumJugadores(2);
                }
                cobro=arcade.calcularPago();
                JOptionPane.showMessageDialog(rootPane,"Valor a cobrar: "+cobro+"$"
                           ,"Cobro",JOptionPane.INFORMATION_MESSAGE);
                btnGuardarCobro.setEnabled(true);  
            }else{
                JOptionPane.showMessageDialog(rootPane,"Llenar todos los campos","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane,"Ingresar números enteros en Horas","ERROR",JOptionPane.ERROR_MESSAGE);
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(rootPane,"No se calculó el cobro","ERROR",JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"otro error"+e.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCalcularpagoActionPerformed

    private void btnGuardarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCobroActionPerformed
        // TODO add your handling code here:
        PnlCobro.setCobroTotal(cobro);
        FmrMenu.equiposAlquilados.add(arcade);
        llimpiar();
        btnGuardarCobro.setEnabled(false);
        desbloquearCampos();
    }//GEN-LAST:event_btnGuardarCobroActionPerformed

    private void btnCancelarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCobroActionPerformed
        // TODO add your handling code here:
        llimpiar();
        desbloquearCampos();
        btnGuardarCobro.setEnabled(false);
    }//GEN-LAST:event_btnCancelarCobroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIArcade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIArcade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIArcade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIArcade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIArcade().setVisible(true);
            }
        });
    }
    public boolean llenos(){
    boolean txt1=txtHorasAlquiladas.getText().isEmpty();
        if(cmbArcade.getSelectedIndex()!=-1&&txt1!=true
                &&(rbt1.isSelected()||rbt2.isSelected())){
            return true;
        }else{
            return false;
        }
    }
    public void llimpiar(){
    cmbArcade.setSelectedIndex(-1);
    txtHorasAlquiladas.setText(null);
    btgNumJugadores.clearSelection();
    }
    public void bloquearCampos(){
        cmbArcade.setEnabled(false);
        txtHorasAlquiladas.setEnabled(false);
        rbt1.setEnabled(false);
        rbt2.setEnabled(false);
    }
    public void desbloquearCampos(){
        cmbArcade.setEnabled(true);
        txtHorasAlquiladas.setEnabled(true);
        rbt1.setEnabled(true);
        rbt2.setEnabled(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgNumJugadores;
    private javax.swing.JButton btnCalcularpago;
    private javax.swing.JButton btnCancelarCobro;
    private javax.swing.JButton btnGuardarCobro;
    private javax.swing.JComboBox<String> cmbArcade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArcade;
    private javax.swing.JLabel lblHorasAlquiladas;
    private javax.swing.JLabel lblNumJugadores;
    private javax.swing.JRadioButton rbt1;
    private javax.swing.JRadioButton rbt2;
    private javax.swing.JTextField txtHorasAlquiladas;
    // End of variables declaration//GEN-END:variables
}
