/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.arcade.testproyecto;

import javax.swing.JOptionPane;

import poo.clases.proyecto.EquipoRealidadVirtual;
/**
 *
 * @author Milton
 */
public class GUIEquipoRVirtual extends javax.swing.JFrame {
    EquipoRealidadVirtual equipoRV;
    private double cobro;
    
    /**
     * Creates new form GUIEquipoRVirtual
     */
    public GUIEquipoRVirtual() {
        initComponents();
        btnGuardarCobro.setEnabled(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbEquipoVirtual = new javax.swing.JComboBox<>();
        lblEquipo = new javax.swing.JLabel();
        lblRealidadVirtual = new javax.swing.JLabel();
        lblSimulacion = new javax.swing.JLabel();
        cmbTipoSimulacion = new javax.swing.JComboBox<>();
        btnCalcularpago = new javax.swing.JButton();
        btnGuardarCobro = new javax.swing.JButton();
        btnCancelarCobro = new javax.swing.JButton();
        lblHorasAlquiladas = new javax.swing.JLabel();
        txtHorasAlquiladas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Equipo de Realidad Virtual");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipo Realidad Virtual"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbEquipoVirtual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nintendo Labo VR", "Valve Index", "Oculus Rift", "HTC Vive", "Oculus Go" }));
        cmbEquipoVirtual.setSelectedIndex(-1);
        jPanel1.add(cmbEquipoVirtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 155, -1));

        lblEquipo.setForeground(new java.awt.Color(255, 255, 255));
        lblEquipo.setText("Equipo");
        jPanel1.add(lblEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        lblRealidadVirtual.setForeground(new java.awt.Color(255, 255, 255));
        lblRealidadVirtual.setText("realidad Virtual:");
        jPanel1.add(lblRealidadVirtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 20));

        lblSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        lblSimulacion.setText("Tipo de simulación:");
        jPanel1.add(lblSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 20));

        cmbTipoSimulacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conduccion", "Shooter", "Visualización de entornos", "Patinaje" }));
        cmbTipoSimulacion.setSelectedIndex(-1);
        jPanel1.add(cmbTipoSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 155, -1));

        btnCalcularpago.setText("Calcular Cobro");
        btnCalcularpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularpagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        btnGuardarCobro.setText("Guardar Cobro");
        btnGuardarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCobroActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        btnCancelarCobro.setText("Cancelar Cobro");
        btnCancelarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCobroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        lblHorasAlquiladas.setForeground(new java.awt.Color(255, 255, 255));
        lblHorasAlquiladas.setText("Horas alquiladas:");
        jPanel1.add(lblHorasAlquiladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 20));
        jPanel1.add(txtHorasAlquiladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 48, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/background/LogoAZMarco.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularpagoActionPerformed
        // TODO add your handling code here:
        try{
            if(llenos()){
                int horasAlquiladas=Integer.parseInt(txtHorasAlquiladas.getText());
                String tipoDeEquipoVR= (String) cmbEquipoVirtual.getSelectedItem();
                String tipoDeSimulacion= (String) cmbTipoSimulacion.getSelectedItem();
                bloquearCampos();
                equipoRV=new EquipoRealidadVirtual();
                equipoRV.setTipoDeEquipoRV(tipoDeEquipoVR);
                equipoRV.setTipoDeSimulacion(tipoDeSimulacion);
                equipoRV.setHorasDealquiler(horasAlquiladas);  
                cobro=equipoRV.calcularPago();
                JOptionPane.showMessageDialog(rootPane,"Valor a cobrar: "+cobro+"$"
                           ,"Cobro",JOptionPane.INFORMATION_MESSAGE);
                btnGuardarCobro.setEnabled(true);  
            }else{
                JOptionPane.showMessageDialog(rootPane,"Llenar todos los campos","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane,"Ingresar números enteros en horas","ERROR",JOptionPane.ERROR_MESSAGE);
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(rootPane,"No se calculó el cobro","ERROR",JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"otro error"+e.toString(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }            
    }//GEN-LAST:event_btnCalcularpagoActionPerformed

    private void btnGuardarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCobroActionPerformed
        // TODO add your handling code here:
        PnlCobro.setCobroTotal(cobro);
        FmrMenu.equiposAlquilados.add(equipoRV);
        llimpiar();
        btnGuardarCobro.setEnabled(false);
        desbloquearCampos();        
    }//GEN-LAST:event_btnGuardarCobroActionPerformed

    private void btnCancelarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCobroActionPerformed
        // TODO add your handling code here:
        llimpiar();
        desbloquearCampos();
        btnGuardarCobro.setEnabled(false);        
    }//GEN-LAST:event_btnCancelarCobroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEquipoRVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEquipoRVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEquipoRVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEquipoRVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEquipoRVirtual().setVisible(true);
            }
        });
    }
    
    public boolean llenos(){
        if(cmbTipoSimulacion.getSelectedIndex()!=-1&&cmbEquipoVirtual.getSelectedIndex()!=-1
                ){
            return true;
        }else{
            return false;
        }
    }
    public void llimpiar(){
    cmbTipoSimulacion.setSelectedIndex(-1);
    cmbEquipoVirtual.setSelectedIndex(-1);
    txtHorasAlquiladas.setText(null);
    }    
    public void bloquearCampos(){
        cmbTipoSimulacion.setEnabled(false);
        cmbEquipoVirtual.setEnabled(false);
    }    
    
    public void desbloquearCampos(){
        cmbTipoSimulacion.setEnabled(true);
        cmbEquipoVirtual.setEnabled(true);
    }    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularpago;
    private javax.swing.JButton btnCancelarCobro;
    private javax.swing.JButton btnGuardarCobro;
    private javax.swing.JComboBox<String> cmbEquipoVirtual;
    private javax.swing.JComboBox<String> cmbTipoSimulacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblHorasAlquiladas;
    private javax.swing.JLabel lblRealidadVirtual;
    private javax.swing.JLabel lblSimulacion;
    private javax.swing.JTextField txtHorasAlquiladas;
    // End of variables declaration//GEN-END:variables
}
