/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.arcade.testproyecto;

/**
 *
 * @author erick cabezas
 */
public class PnlCobro extends javax.swing.JPanel {
 GUIConsola consola;
 GUIComputadora computadora;
 GUIArcade arcade;
 GUIEquipoRVirtual equipoRVirtual;
 private static double cobroTotal;
    /**
     * Creates new form pnlCobro
     */
    public PnlCobro() {
        initComponents();
        consola=new GUIConsola();
        computadora = new GUIComputadora();
        arcade=new GUIArcade();
        equipoRVirtual=new GUIEquipoRVirtual();
        
    }
    
    public static double getCobroTotal() {
        return cobroTotal;
    }

    public static void setCobroTotal(double cobro) {
        PnlCobro.cobroTotal += cobro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsola = new javax.swing.JButton();
        lblConsola = new javax.swing.JLabel();
        lblComputadora = new javax.swing.JLabel();
        lblArcade = new javax.swing.JLabel();
        lblEquipo = new javax.swing.JLabel();
        lblRealidadVirtual = new javax.swing.JLabel();
        btnRVirtual = new javax.swing.JButton();
        btnArcade = new javax.swing.JButton();
        btnComputadora = new javax.swing.JButton();

        btnConsola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Super_TES_icon-icons.com_66600.png"))); // NOI18N
        btnConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsolaActionPerformed(evt);
            }
        });

        lblConsola.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConsola.setText("Consola:");

        lblComputadora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblComputadora.setText("Computadora:");

        lblArcade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblArcade.setText("Arcade:");

        lblEquipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEquipo.setText("Equipo");

        lblRealidadVirtual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRealidadVirtual.setText("realidad Virtual:");

        btnRVirtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/augmentedreality-15_111400.png"))); // NOI18N
        btnRVirtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRVirtualActionPerformed(evt);
            }
        });

        btnArcade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Galaga_Arcade_icon-icons.com_75284.png"))); // NOI18N
        btnArcade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcadeActionPerformed(evt);
            }
        });

        btnComputadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/computer_84314.png"))); // NOI18N
        btnComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsola)
                            .addComponent(lblComputadora))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComputadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRealidadVirtual)
                            .addComponent(lblArcade)
                            .addComponent(lblEquipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRVirtual, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnArcade, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblConsola))
                    .addComponent(btnConsola))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblComputadora))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComputadora)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnArcade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblArcade)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRVirtual, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRealidadVirtual)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsolaActionPerformed
        // TODO add your handling code here:
        consola.setVisible(true);
        
    }//GEN-LAST:event_btnConsolaActionPerformed

    private void btnRVirtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRVirtualActionPerformed
        // TODO add your handling code here:
        equipoRVirtual.setVisible(true);
    }//GEN-LAST:event_btnRVirtualActionPerformed

    private void btnArcadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcadeActionPerformed
        // TODO add your handling code here:
        arcade.setVisible(true);
    }//GEN-LAST:event_btnArcadeActionPerformed

    private void btnComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadoraActionPerformed
        // TODO add your handling code here:
        computadora.setVisible(true);
    }//GEN-LAST:event_btnComputadoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArcade;
    private javax.swing.JButton btnComputadora;
    private javax.swing.JButton btnConsola;
    private javax.swing.JButton btnRVirtual;
    private javax.swing.JLabel lblArcade;
    private javax.swing.JLabel lblComputadora;
    private javax.swing.JLabel lblConsola;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblRealidadVirtual;
    // End of variables declaration//GEN-END:variables
}
