/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.arcade.testproyecto;

import javax.swing.table.DefaultTableModel;
import static poo.arcade.testproyecto.FmrMenu.equiposAlquilados;
import poo.clases.proyecto.Maquina;

/**
 *
 * @author erick cabezas
 */
public class PnlCuenta extends javax.swing.JPanel {
    DefaultTableModel dtmModelo;

    /**
     * Creates new form PnlCuenta
     */
    public PnlCuenta() {
        initComponents();
        dtmModelo= new DefaultTableModel();// inicializamos el modelo de la tabla
        dtmModelo.addColumn("Equipo");
        dtmModelo.addColumn("Horas Alquiladas");
        dtmModelo.addColumn("Valor Por Hora");
        dtmModelo.addColumn("Valor Cobrado");
        tblCuenta.setModel(dtmModelo);
    }
    public void llenarTabla(){
        dtmModelo.setRowCount(0);
        for(Maquina eqp: FmrMenu.equiposAlquilados){
            dtmModelo.addRow(new Object[]{eqp.toString(),eqp.getHorasDealquiler(),eqp.getValorPorHora()
            ,eqp.getCobrado()});
            
        }
        lblCobroTotal.setText(Double.toString(PnlCobro.getCobroTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuenta = new javax.swing.JTable();
        lblCobrototal = new javax.swing.JLabel();
        lblCobroTotal = new javax.swing.JLabel();
        lblDolar = new javax.swing.JLabel();

        tblCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCuenta);

        lblCobrototal.setText("Ingresos totales:");

        lblCobroTotal.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lblCobroTotal.setText(".......");

        lblDolar.setForeground(new java.awt.Color(0, 102, 0));
        lblDolar.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCobrototal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCobroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lblDolar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCobrototal)
                    .addComponent(lblCobroTotal)
                    .addComponent(lblDolar))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCobroTotal;
    private javax.swing.JLabel lblCobrototal;
    private javax.swing.JLabel lblDolar;
    private javax.swing.JTable tblCuenta;
    // End of variables declaration//GEN-END:variables
}
